// ─── CRBRO Query Synonyms ────────────────────────────────────────
// A short bilingual table of everyday agency / development vocabulary.
//
// Applied at query time only, inside variants(): a synonym counts as the SAME
// query term, so a fact found through "hosting" for a question about
// "alojamiento" scores exactly like an exact match — no more, no less. It
// cannot invent a term that was not asked for, only widen the spelling of
// one that was. Both directions are listed explicitly; nothing is inferred.
//
// Keys and values are folded (lowercase, no accents, ñ → n) because that is
// what tokenize() produces. Keep entries generic: a pair that only makes
// sense for one benchmark query is overfitting, not vocabulary.
//
// Off with CRBRO_SYNONYMS=0 — the retrieval benchmark measures both ways.

export const SYNONYMS: Record<string, string[]> = {
  // ── web, sites, pages ──
  web: ['sitio', 'pagina', 'website', 'site'],
  webs: ['sitios', 'paginas', 'websites'],
  sitio: ['web', 'site', 'pagina'],
  sitios: ['webs', 'sites', 'paginas'],
  pagina: ['web', 'page', 'sitio'],
  paginas: ['webs', 'pages', 'sitios'],
  website: ['web', 'sitio'],
  landing: ['landings', 'pagina'],

  // ── hosting, servers ──
  hosting: ['alojamiento', 'servidor', 'server', 'vps'],
  alojamiento: ['hosting', 'servidor', 'server'],
  alojado: ['hosting', 'servidor', 'alojamiento'],
  alojada: ['hosting', 'servidor', 'alojamiento'],
  alojados: ['hosting', 'servidor', 'alojamiento'],
  alojadas: ['hosting', 'servidor', 'alojamiento'],
  servidor: ['server', 'hosting', 'vps', 'maquina'],
  servidores: ['servers', 'hosting', 'maquinas'],
  server: ['servidor', 'hosting'],
  vps: ['servidor', 'hosting'],

  // ── email ──
  email: ['correo', 'mail', 'mailing', 'newsletter'],
  emails: ['correos', 'mails'],
  correo: ['email', 'mail', 'mailing'],
  correos: ['emails', 'mails'],
  mail: ['email', 'correo'],
  mailing: ['email', 'correo', 'newsletter'],
  newsletter: ['boletin', 'email', 'mailing'],
  boletin: ['newsletter', 'email'],

  // ── security ──
  seguridad: ['security', 'proteccion', 'firewall'],
  security: ['seguridad', 'proteccion'],
  proteccion: ['seguridad', 'protection', 'firewall'],
  firewall: ['seguridad', 'proteccion'],

  // ── money ──
  coste: ['precio', 'tarifa', 'cost', 'price'],
  costes: ['precios', 'tarifas', 'costs'],
  costo: ['precio', 'coste', 'tarifa'],
  precio: ['coste', 'tarifa', 'price'],
  precios: ['costes', 'tarifas', 'prices'],
  tarifa: ['precio', 'coste', 'pricing'],
  tarifas: ['precios', 'costes'],
  price: ['precio', 'coste'],
  pricing: ['precios', 'tarifas'],
  presupuesto: ['budget', 'cotizacion', 'quote'],
  budget: ['presupuesto'],
  ingresos: ['revenue', 'facturacion', 'mrr'],
  revenue: ['ingresos', 'facturacion'],
  factura: ['invoice', 'facturacion'],
  facturas: ['invoices', 'facturacion'],
  facturacion: ['facturas', 'billing', 'invoicing', 'cobro'],
  billing: ['facturacion', 'facturas'],
  cobro: ['pago', 'facturacion', 'cobros'],
  cobros: ['pagos', 'facturacion'],
  pago: ['payment', 'cobro', 'pagos'],
  pagos: ['payments', 'cobros'],
  payment: ['pago', 'cobro'],

  // ── moving sites ──
  migracion: ['traslado', 'mudanza', 'migration', 'mover'],
  migraciones: ['traslados', 'migrations'],
  migration: ['migracion', 'traslado'],
  traslado: ['migracion', 'mudanza', 'mover'],
  mudanza: ['migracion', 'traslado'],
  mover: ['migracion', 'traslado', 'mudanza'],

  // ── links, code, repos ──
  enlace: ['link', 'url'],
  enlaces: ['links', 'urls'],
  link: ['enlace', 'url'],
  links: ['enlaces', 'urls'],
  url: ['enlace', 'link'],
  urls: ['enlaces', 'links'],
  codigo: ['code', 'repositorio', 'repo'],
  code: ['codigo'],
  repositorio: ['repo', 'repository', 'github', 'codigo'],
  repo: ['repositorio', 'repository', 'github'],
  repository: ['repositorio', 'repo'],

  // ── credentials, accounts ──
  contrasena: ['password', 'clave', 'credencial'],
  password: ['contrasena', 'clave'],
  clave: ['key', 'contrasena', 'password'],
  claves: ['keys', 'contrasenas'],
  credencial: ['credential', 'clave', 'token'],
  credenciales: ['credentials', 'claves'],
  token: ['credencial', 'clave'],
  usuario: ['user', 'cuenta'],
  usuarios: ['users', 'cuentas'],
  user: ['usuario', 'cuenta'],
  cuenta: ['account', 'usuario'],
  cuentas: ['accounts', 'usuarios'],
  account: ['cuenta', 'usuario'],

  // ── problems ──
  error: ['fallo', 'bug', 'errores'],
  errores: ['fallos', 'bugs'],
  fallo: ['error', 'bug', 'problema'],
  fallos: ['errores', 'bugs', 'problemas'],
  bug: ['error', 'fallo'],
  problema: ['fallo', 'error', 'issue', 'incidencia'],
  problemas: ['fallos', 'errores', 'incidencias'],
  incidencia: ['incidente', 'problema', 'fallo'],

  // ── media, content ──
  imagen: ['foto', 'image', 'picture'],
  imagenes: ['fotos', 'images'],
  foto: ['imagen', 'photo', 'fotografia'],
  fotos: ['imagenes', 'photos', 'fotografias'],
  fotografia: ['foto', 'imagen'],
  formulario: ['form', 'formularios'],
  formularios: ['forms', 'formulario'],
  form: ['formulario'],
  plantilla: ['template', 'theme', 'tema'],
  plantillas: ['templates', 'themes'],
  template: ['plantilla', 'tema'],
  tema: ['theme', 'plantilla'],
  theme: ['tema', 'plantilla'],

  // ── operations ──
  copia: ['backup', 'respaldo'],
  copias: ['backups', 'respaldos'],
  backup: ['copia', 'respaldo'],
  backups: ['copias', 'respaldos'],
  respaldo: ['backup', 'copia'],
  despliegue: ['deploy', 'publicar', 'deployment'],
  deploy: ['despliegue', 'publicar'],
  publicar: ['publish', 'deploy', 'despliegue'],
  dominio: ['domain', 'dominios', 'dns'],
  dominios: ['domains', 'dns'],
  domain: ['dominio'],
  database: ['base', 'bd'],
  configuracion: ['config', 'settings', 'ajustes'],
  config: ['configuracion', 'settings'],
  ajustes: ['settings', 'configuracion'],
  settings: ['ajustes', 'configuracion'],
  actualizacion: ['update', 'upgrade', 'actualizar'],
  actualizar: ['update', 'actualizacion'],
  update: ['actualizacion', 'actualizar'],
  version: ['release', 'versiones'],
  mantenimiento: ['maintenance'],
  maintenance: ['mantenimiento'],
  entorno: ['environment', 'staging', 'local'],
  entornos: ['environments', 'staging'],
  environment: ['entorno'],
  staging: ['entorno', 'pruebas', 'test'],
  pruebas: ['test', 'tests', 'testing', 'staging'],
  prueba: ['test', 'pruebas'],
  test: ['pruebas', 'prueba', 'testing'],
  tests: ['pruebas', 'testing'],

  // ── business ──
  cliente: ['customer', 'client', 'clientes'],
  clientes: ['customers', 'clients'],
  customer: ['cliente'],
  client: ['cliente'],
  contrato: ['contract', 'acuerdo'],
  contract: ['contrato'],
  acuerdo: ['contrato', 'agreement'],
  objetivo: ['goal', 'meta', 'target'],
  objetivos: ['goals', 'metas'],
  goal: ['objetivo', 'meta'],
  reunion: ['meeting', 'llamada'],
  meeting: ['reunion'],
  tienda: ['shop', 'store', 'ecommerce', 'comercio'],
  ecommerce: ['tienda', 'shop', 'woocommerce'],
  shop: ['tienda'],
  producto: ['product', 'productos'],
  productos: ['products', 'catalogo'],
  catalogo: ['catalog', 'productos'],
  pedido: ['order', 'pedidos'],
  pedidos: ['orders'],
  suscripcion: ['subscription', 'plan', 'membresia'],
  suscripciones: ['subscriptions', 'planes', 'licencias'],
  subscription: ['suscripcion', 'plan'],
  licencia: ['license', 'suscripcion'],
  licencias: ['licenses', 'suscripciones'],
  membresia: ['membership', 'suscripcion', 'pase'],
  pase: ['membresia', 'suscripcion'],

  // ── marketing ──
  anuncios: ['ads', 'publicidad', 'campanas'],
  ads: ['anuncios', 'publicidad', 'campanas'],
  publicidad: ['ads', 'anuncios', 'campanas'],
  campana: ['campaign', 'campanas'],
  campanas: ['campaigns', 'ads', 'anuncios'],
  posicionamiento: ['seo', 'ranking'],
  seo: ['posicionamiento', 'ranking', 'keywords'],
  trafico: ['traffic', 'visitas'],
  visitas: ['trafico', 'traffic'],

  // ── tools, software, AI ──
  herramienta: ['tool', 'programa'],
  herramientas: ['tools', 'programas'],
  tool: ['herramienta'],
  tools: ['herramientas'],
  programa: ['software', 'herramienta', 'aplicacion', 'app'],
  aplicacion: ['app', 'programa'],
  aplicaciones: ['apps', 'programas'],
  app: ['aplicacion', 'application'],
  automatizacion: ['automation', 'workflow', 'automatizar'],
  automatizaciones: ['automations', 'workflows'],
  automation: ['automatizacion', 'workflow'],
  workflow: ['flujo', 'automatizacion'],
  workflows: ['flujos', 'automatizaciones'],
  flujo: ['workflow', 'flujos'],
  busqueda: ['search', 'buscar', 'buscador'],
  search: ['busqueda', 'buscar'],
  buscar: ['search', 'busqueda'],
  ia: ['ai', 'inteligencia', 'llm', 'modelo'],
  ai: ['ia', 'inteligencia'],
  inteligencia: ['ia', 'ai'],
  modelo: ['model', 'llm', 'ia'],
  datos: ['data', 'base'],
  data: ['datos'],
};
